### ISSUE TITLE
enigma en castillo

### ISSUE THREAD

**Issue by b4zz4** [fauno/remaster-blaster#12]
http://beta.babelzilla.org/projects/p/Enigmail/language/es-ES/
supuestamente esta 100% traducido

podemos descargar los archivos de ahí y parchar el xpi

**Comment by fauno** [comment]
lo probaste? recuerdo que algunas cosas estaban en castellano y otras no en el xpi que trae la iso

**Comment by fauno** [comment]
dice que puedo descargar un xpi con las traducciones aplicadas si estoy logueado, tenes cuenta ahi?

**Comment by fauno** [comment]
me fije y ya las trae las traducciones, pero colgué en fijarme si ya se aplican

**Comment by fauno** [comment]
aca me dicen que sale en castellano asi que cierro esto
