### ISSUE TITLE
problemas con IDJC

### ISSUE THREAD

**Issue by b4zz4** [fauno/remaster-blaster#19]
Parece que hay problemas con la prioridad del sonido y el grupo

idjc
jack client ID: idjc_default
launching backend
backend launch attempt 1
jackd 0.122.0
Copyright 2001-2009 Paul Davis, Stephane Letz, Jack O'Quinn, Torben Hohn and others.
jackd comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details

JACK is running in realtime mode, but you are not allowed to use realtime scheduling.
Please check your /etc/security/limits.conf for the following line
and correct/add it if necessary:

  @audio          -       rtprio          99

After applying these changes, please re-login in order for them to take effect.

You don't appear to have a sane system configuration. It is very likely that you
encounter xruns. Please apply all the above mentioned changes and start jack again!
main.c: jack_client_open failedawaiting reply

**Comment by fauno** [comment]
@b4zz4 me decis como lo tenes ahora y por que valor hay que cambiarlo?
