### ISSUE TITLE
errores en SSL

### ISSUE THREAD

**Issue by b4zz4** [fauno/remaster-blaster#6]
![screenshot - 051214 - 14 11 21](https://cloud.githubusercontent.com/assets/643833/5319778/19ac8526-7c8b-11e4-8467-258b8f2436d6.png)
![screenshot - 051214 - 14 12 13](https://cloud.githubusercontent.com/assets/643833/5319779/19c0524a-7c8b-11e4-976f-9c514cf7bfdd.png)

Estos dos servidores dan errores similares

Con freenode no tiene problemas :(

**Comment by fauno** [comment]
estuve probando con la versión nueva y funca bien
